### ISSUE TITLE
Error in connection

### ISSUE THREAD

**Issue by sunilsql** [schemaorg/schemaorg#2131]
I don't understand where I went wrong...

D:\>java -jar schemaspy-6.0.0.jar -t mssql08-jtds -host XPO-H6T95S2-L -port 1433 -db AdventureWorks2016CTP3 -u sa -p test -s person -o D:\adv\ -gv "C:\Program Files (x86)\Graphviz2.38" -dp "D:\jtds-1.3.1-dist\jtds-1.3.1.jar" -debug
  ____       _                          ____
 / ___|  ___| |__   ___ _ __ ___   __ _/ ___| _ __  _   _
 \___ \ / __| '_ \ / _ \ '_ ` _ \ / _` \___ \| '_ \| | | |
  ___) | (__| | | |  __/ | | | | | (_| |___) | |_) | |_| |
 |____/ \___|_| |_|\___|_| |_| |_|\__,_|____/| .__/ \__, |
                                             |_|    |___/

                                              6.0.0

SchemaSpy generates an HTML representation of a database schema's relationships.
SchemaSpy comes with ABSOLUTELY NO WARRANTY.
SchemaSpy is free software and can be redistributed under the conditions of LGPL version 3 or later.
http://www.gnu.org/licenses/

INFO  - Starting Main v6.0.0 on XPO-H6T95S2-L with PID 24128 (D:\schemaspy-6.0.0.jar started by xskumarjanjirala in D:\)
INFO  - The following profiles are active: default
INFO  - Started Main in 0.94 seconds (JVM running for 1.298)
DEBUG - Debug enabled
INFO  - Configuration file not found
INFO  - Starting schema analysis
DEBUG - Resolving dbType: mssql08-jtds ->
        /D:/schemaspy-6.0.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql08-jtds.properties ->
        /D:/schemaspy-6.0.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql05-jtds.properties ->
        /D:/schemaspy-6.0.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql-jtds.properties ->
        /D:/schemaspy-6.0.0.jar!/BOOT-INF/classes!/org/schemaspy/types/mssql.properties
DEBUG - DbSpecificOption name: 'hostOptionalPort' value: 'XPO-H6T95S2-L:1433' description: 'null'
DEBUG - DbSpecificOption name: 'db' value: 'AdventureWorks2016CTP3' description: 'database name  '
WARN  - Connection Failure
org.schemaspy.model.ConnectionFailure: Failed to connect to database URL [jdbc:jtds:sqlserver://XPO-H6T95S2-L:1433/AdventureWorks2016CTP3] Network error IOException: Connection refused: connect
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:101)
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:75)
        at org.schemaspy.service.SqlService.connect(SqlService.java:68)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:186)
        at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:107)
        at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:97)
        at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:86)
        at org.schemaspy.Main.main(Main.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.sql.SQLException: Network error IOException: Connection refused: connect
        at net.sourceforge.jtds.jdbc.JtdsConnection.<init>(JtdsConnection.java:436)
        at net.sourceforge.jtds.jdbc.Driver.connect(Driver.java:184)
        at org.schemaspy.DbDriverLoader.getConnection(DbDriverLoader.java:94)
        ... 15 common frames omitted
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at net.sourceforge.jtds.jdbc.SharedSocket.createSocketForJDBC3(SharedSocket.java:288)
        at net.sourceforge.jtds.jdbc.SharedSocket.<init>(SharedSocket.java:251)
        at net.sourceforge.jtds.jdbc.JtdsConnection.<init>(JtdsConnection.java:331)
        ... 17 common frames omitted

**Comment by nicolastorzec** [comment]
This issue doesn't belong here.
