### ISSUE TITLE
ImportError: No module named dev_appserver when running ./deploypythonapp.sh

### ISSUE THREAD

**Issue by philbarker** [schemaorg/schemaorg#2403]
```
$ ./deploypythonapp.sh 
Deploy sdopythonapp application... 
Checking sdopythonapp is upto date

Run application from Local or Remote configuration files?
Local: deployed with pythonapp to gcloud
Remote: from remote URL eg. https://raw.githubusercontent.com/... 
Local or Remote? [L|R]: L
Running local preprepare script
runpythonpreprepare.sh:

Build site static files Y/N [Y]: 

Version for release files: 5.0

buildreleasefiles.sh:About to build release files for version 5.0
      Including extensions: attic auto bib health-lifesci pending meta
Continue? y/n: y

Running Unit Tests... 
Traceback (most recent call last):
  File "./scripts/run_tests.py", line 110, in <module>
    main('./tests/', args)
  File "./scripts/run_tests.py", line 78, in main
    import dev_appserver
ImportError: No module named dev_appserver
```
Same happens with `./runpythonapp.sh` if the Build static files option is changed to Y from default N.  Both run and deploy work OK if this option is set to N.

**Comment by philbarker** [comment]
Thanks to @RichardWallis,  traced the error to not having APP_ENGINE environment varible set. 
Fixed with
```
$ which dev_appserver.py
{path_to_sdk}/bin/dev_appserver.py
$ export APP_ENGINE={path_to_sdk}/bin/google-cloud-sdk/platform/google_appengine/
```

**Comment by RichardWallis** [comment]
Thanks to @philbarker for helping to track this down in his environment!
