### ISSUE TITLE
Example parser crashes on empty file

### ISSUE THREAD

**Issue by MatthiasWiesmann** [schemaorg/schemaorg#3075]
The code that parses examples crashes when it encounters an empty file.

# Steps to reproduce

    touch data/ext/pending/issue-xxx-examples.txt
    ./software/util/runtests.py 

# Expected result

Some error message explaining that file `data/ext/pending/issue-xxx-examples.txt` is incorrect

# Actual Result

```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/wiesmann/Projects/Google/schema_playground/schemaorg/software/tests/test_basics.py", line 35, in <module>
    SchemaExamples.loadExamplesFiles("default")
  File "/Users/wiesmann/Projects/Google/schema_playground/schemaorg/software/SchemaExamples/schemaexamples.py", line 199, in loadExamplesFiles
    for example in parser.parse(f):
  File "/Users/wiesmann/Projects/Google/schema_playground/schemaorg/software/SchemaExamples/schemaexamples.py", line 383, in parse
    examples.append(Example(self.terms, self.preMarkupStr, self.microdataStr, self.rdfaStr, self.jsonStr, self.exmeta)) # should flush last one
  File "/Users/wiesmann/Projects/Google/schema_playground/schemaorg/software/SchemaExamples/schemaexamples.py", line 28, in __init__
    log.info("No terms for ex: %s in file %s" % (exmeta["filepos"],emeta["file"]) )
KeyError: 'filepos'
```

# Note

I have a fix, you can assign the issue to me.

**Comment by MatthiasWiesmann** [comment]
Fix is here: https://github.com/schemaorg/schemaorg/pull/3076/commits

**Comment by danbri** [comment]
@RichardWallis - can you take the fix?

**Comment by MatthiasWiesmann** [comment]
Fix is in.

**Comment by danbri** [comment]
Thanks again, @MatthiasWiesmann :)
